- pkgs/phps.nix
This PR should fix the `oci8` extension on `php56` once `flake.lock` is updated to anything past https://github.com/NixOS/nixpkgs/pull/108904.
> php.extensions.oci8: set correct version depending on php version

- pkgs/phps.nix
`php56.extensions.apcu` doesn't build. Reviewing some [history](https://github.com/NixOS/nixpkgs/blob/release-18.09/pkgs/top-level/php-packages.nix#L12) it looks like `apcu` support for `php56` is capped at `4.0.11`. Probably.
> php56: fix apcu

- .github/workflows/build.yaml
- flake.lock
- pkgs/package-overrides.nix
- packages the `mysql` extension for ancient applications which need it
- resolves #27
- **requires a pulling in a recent version of `nixpkgs` before this will work**
> php.extenions.mysql: init

- .github/workflows/build.yaml
- pkgs/package-overrides.nix
- the `--with-mysql-sock` option didn't exist in `php` 5.6
**before**
```
php -r "echo 'path: ' . ini_get('mysqli.default_socket') . PHP_EOL;"
path:
```
**after**
```
php -r "echo 'path: ' . ini_get('mysqli.default_socket') . PHP_EOL;"
path: /run/mysqld/mysqld.sock
```
The same is true for `pdo_mysql.default_socket`.
> php56.extensions.mysqli,pdo_mysql: set default unix socket path

- pkgs/package-overrides.nix
- packages the `mssql` extension for ancient applications which need it
- extension was available in prior versions of `nixpkgs`
> php56.extensions.mssql: init

- pkgs/package-overrides.nix
This breaks for example in hydra builds
> fix: switch to pkgs.fetchurl as builtins.fetchurl is not avail in restricted mode

- .github/workflows/build.yaml
- pkgs/package-overrides.nix
Composer 2.1.6 switched PHAR signatures to SHA512 (https://github.com/composer/composer/commit/e49f24e3550329913f5eb5e92669f403c9484a91). On older versions of PHP, support for SHA-256 and SHA-512 is conditional on `hash` extension being enabled at compile time. Since we build `hash` extension in a separate package, `phar` extension assumes it will not be available and comments out the code paths, causing the following error:
Fatal error: Uncaught PharException: phar "/nix/store/rf48l2wpxqi3vfadf3vf1z3pq35p7d5i-php-composer-2.1.6/libexec/composer/composer.phar" has a unsupported signature in /nix/store/rf48l2wpxqi3vfadf3vf1z3pq35p7d5i-php-composer-2.1.6/libexec/composer/composer.phar:23
Stack trace:
#0 /nix/store/rf48l2wpxqi3vfadf3vf1z3pq35p7d5i-php-composer-2.1.6/libexec/composer/composer. …
> Downgrade composer on PHP ≤ 7.3

- flake.lock
- pkgs/package-overrides.nix
- pkgs/phps.nix
Composer 2.1.6 switched PHAR signatures to SHA512 (https://github.com/composer/composer/commit/e49f24e3550329913f5eb5e92669f403c9484a91). On older versions of PHP, support for SHA-256 and SHA-512 is conditional
on hash extension being enabled at compile time. Since we build hash extension in a separate package, phar extension assumes it will not be available and comments out the code paths, causing the following error
Fatal error: Uncaught PharException: phar "/nix/store/rf48l2wpxqi3vfadf3vf1z3pq35p7d5i-php-composer-2.1.6/libexec/composer/composer.phar" has a unsupported signature in /nix/store/rf48l2wpxqi3vfadf3vf1z3pq35p7d5i-php-composer-2.1.6/libexec/composer/composer.phar:23
Stack trace:
#0 /nix/store/rf48l2wpxqi3vfadf3vf1z3pq35p7d5i-php-composer-2.1.6/libexec/composer/composer.phar(23 …
> Fix composer on PHP ≤ 7.3

- .github/workflows/build.yaml
- pkgs/package-overrides.nix
This fix select the proper Xdebug version according to a given PHP version.
My code is pretty naïve since I discovered Nix a couple of days ago :) Feel free to suggest improvements :)
> fix: xdebug versions

- .github/workflows/build.yaml
- README.md
- flake.lock
- flake.nix
- pkgs/phps.nix
PHP 8.1.1 has just been merged in Nixos (https://github.com/NixOS/nixpkgs/pull/147411).
This PR add support for PHP 8.1.1 in this package.
Tests are failing for now because `nixos-unstable` hasn't been updated yet.
> feat: Add PHP81.

- pkgs/package-overrides.nix
This fixes compilation of the PDO extension on Darwin. The [php-src commit containing the patch](https://github.com/php/php-src/commit/11eed9f3ba7429be467b54d8407cfbd6bd7e6f3a) first appeared in PHP 7.2.2, so I have applied it to versions prior to 7.2.
> Fix PDO builds on Darwin for PHP <= 7.1

- .github/workflows/build.yaml
- checks.nix
- flake.nix
This will make it easier to run checks locally (e.g. using `nix flake check`). Additionally, it will allow us to generate the CI tasks automatically and support different sets of checks for different platforms easily.
> Move checks into the flake

- pkgs/phps.nix
This PR is trying to figure out why PHP intl extension cannot be built on MacOS.
See those links:
* https://bugs.php.net/bug.php?id=76826
* https://github.com/phpbrew/phpbrew/issues/962
* https://github.com/docker-library/php/issues/307
> Fix PHP72 builds on MacOS

- .github/workflows/build.yaml
- pkgs/phps.nix
Picked from https://github.com/fossar/nix-phps/pull/104
> Coding style cleanups

- flake.lock
- pkgs/package-overrides.nix
- pkgs/patches/mysqlnd_fix_compression.patch
- pkgs/patches/zend_file_cache_config.patch
- pkgs/patches/zlib-darwin-tests.patch
- pkgs/phps.nix
Still need to copy the generic.nix fixes from https://github.com/NixOS/nixpkgs/pull/172256, and double check that we are copying stuff correctly.
> flake: Update & re-introduce checks removed in Nixpkgs

- pkgs/package-overrides.nix
See this commit https://github.com/NixOS/nixpkgs/commit/42b3cedbb5b880e035258b86b2565a9341d4413b from https://github.com/NixOS/nixpkgs/pull/174555 for the reason of this PR.
> `oci8` - Use `overrideAttrs` instead of `override`.

- pkgs/php/7.4.nix
News: https://www.php.net/archive/2022.php#2022-11-03-1
```
The PHP development team announces the immediate availability of PHP 7.4.33.
This is security release that fixes an OOB read due to insufficient input validation in imageloadfont(), and a buffer overflow in hash_update() on long parameter.
All PHP 7.4 users are encouraged to upgrade to this version.
```
> php74: 7.4.30 -> 7.4.33

- .github/workflows/build.yaml
- checks.nix
- pkgs/package-overrides.nix
Add support for XDebug 3.2.0, which is supporting PHP 8.2.
This should fix #172
> php.extensions.xdebug: add support for php82

- pkgs/package-overrides.nix
Related to https://github.com/NixOS/nixpkgs/pull/205180
> fix: fix `xdebug` extension for PHP 7.

- pkgs/php/7.3.nix
- pkgs/phps.nix
> php73: fix builds on darwin architecture

- .github/workflows/editorconfig-checks.yaml
The action recently started checking `.git/config`, causing the workflow to fail.
This is likely caused by the recent bump of editorconfig’s Docker image from 2.4.0 to 2.7.0.
Curiously, the issue does not occur when using 2.7.0 via the action from the main branch so let’s switch to that, pinning the commit since there is no tag yet.
While at it, let’s also pin the editorconfig version to reduce the change of possible breakage in the future.
> ci/editorconfig: Update the action to HEAD

- pkgs/lib.nix
- pkgs/package-overrides.nix
Nixpkgs disables some opcache tests on Darwin by removing them:
https://github.com/NixOS/nixpkgs/commit/7a09daa9139d543129a56f50b74e152843579f3e
But the test was only introduced in 7.2.20 so we cannot remove it in older versions:
https://github.com/php/php-src/commit/42c7d5106b03e0a07cfa6f40ed2d883575d6fcc3
It would cause “No such file or directory” error.
Let’s remove the line on affected PHP versions.
Using `removeLines` will let us know loudly when the removal is no longer necessary.
Supersedes https://github.com/fossar/nix-phps/pull/212
> php≤71.extensions.opcache: Fix build on Darwin

- .github/workflows/build.yaml
Also fix `cachix/cachix-action` version number
Context: https://discourse.nixos.org/t/nix-2-14-0-released/25900/4?u=drupol
> ci: bump `cachix/install-nix-action`

- pkgs/phps.nix
> php: remove `meta.knownVulnerabilities`

- .github/workflows/build.yaml
- pkgs/package-overrides.nix
Listing available extensions for a PHP derivations is currently broken.
Reasons are:
1. Syntax errors
2. Wrong way of handling extensions
3. Missing upstream extension, not defined in here
Therefore, the idea behind this PR is to be able to list all the available extensions for any `php` derivations, without errors.
Doing (replace `XX` with the PHP version): 
```shell
NIXPKGS_ALLOW_BROKEN=1 \
NIXPKGS_ALLOW_INSECURE=1 \
NIXPKGS_ALLOW_UNFREE=1 \
nix eval --json --impure --expr '(import ./.).packages.x86_64-linux.phpXX.extensions'
```
should not throw any error, just list the available extensions.
This PR:
- Fix #245
> extensions: fix extensions handling

- pkgs/package-overrides.nix
Issue introduced in #246 
I still don't get why doing:
```shell
nix build --impure --expr '(import ./.).outputs.packages.${builtins.currentSystem}.php82.withExtensions({ enabled, all }: (enabled ++ all.blackfire))'
```
result in:
> blackfire: fix typo in PHP version

- pkgs/extensions/blackfire/1.50.0.nix
- pkgs/extensions/blackfire/1.88.1.nix
- pkgs/package-overrides.nix
Goal of this PR:
- Restore `blackfire` extension for PHP 8.0 since it has been removed in https://github.com/NixOS/nixpkgs/pull/239228 and https://github.com/NixOS/nixpkgs/pull/239049
This command should be successful: `nix build .#php80.extensions.blackfire`
It was failing because the `finalAttrs` pattern hasn't been implemented.
I made a PR to implement it here https://github.com/NixOS/nixpkgs/pull/241072, once that PR is propagated to `nixpkgs-unstable` (https://nixpk.gs/pr-tracker.html?pr=241072), we can revisit this PR.
Related PR: https://github.com/NixOS/nixpkgs/pull/241543
> phpExtensions.blackfire: restore on PHP 8.0

- pkgs/enchant/1.x.nix
- pkgs/package-overrides.nix
This PR
- Should fix #247
Source of `enchant1` derivation: https://github.com/matthewbauer/nixpkgs/blob/ba76fa91c762160e0d75a4cba74b44a0c3f911e7/pkgs/development/libraries/enchant/1.x.nix
> extensions: fix `enchant` extension for PHP < 8

- pkgs/package-overrides.nix
Version 0.75.0 is the last version I can build using PHP 5.6.
> extensions: `datadog_trace` make sure it throws when using unsupported PHP versions

- pkgs/enchant/1.x.nix
- pkgs/enchant/fix-libtool-build.patch
Adding the patch by default, it doesn't make any difference on Linux platforms, only for Darwin.
See: https://github.com/loophp/nix-shell/actions/runs/5477574995/jobs/9976841537
See: https://bugs.gentoo.org/630072
> extensions: `enchant`: fix build on darwin

- pkgs/package-overrides.nix
See https://www.php.net/manual/en/mongodb.requirements.php
Also pushing an update upstream to update the extension at https://github.com/NixOS/nixpkgs/pull/242366
> extensions: `mongodb`: fix extension version for php < 7

- pkgs/package-overrides.nix
https://pecl.php.net/package/maxminddb
> phpExtensions.maxminddb: requires PHP >= 7.2

- pkgs/package-overrides.nix
https://pecl.php.net/package-changelog.php?package=igbinary
Upstream PR to add support for PHP 8.3: https://github.com/NixOS/nixpkgs/pull/242900
> phpExtensions.igbinary: add support for PHP 5.6

- pkgs/package-overrides.nix
Is there a better way to let the user know that there are version of `grpc` that works on PHP 5.6 but we don't currently support it ?
I've been trying to compile the version 1.33.1 which is the latest `grpc` stable version for PHP 5.6, but I couldn't make it work (issue with abseil-cpp library). I guess there would be a way to fix this, but does it worth it ?
> phpExtensions.grpc: disable on php56

- pkgs/package-overrides.nix
See the README at https://github.com/goodspb/pdlib
> phpExtensions.pdlib: require PHP >= 7

- pkgs/package-overrides.nix
> phpExtensions.pdlib: fix throw message typo, require PHP >= 7

- .github/workflows/build.yaml
- pkgs/package-overrides.nix
Since a week or two (_I can't really tell when_), it's not possible to build PHP < 8.1 on Darwin. This PR is to investigate why.
To test on Darwin:
0. Clone this repo: `git@github.com:fossar/nix-phps.git`
1. Apply the following patch: 
```diff
diff --git i/pkgs/package-overrides.nix w/pkgs/package-overrides.nix
index 6cd988d..1691c5e 100644
--- i/pkgs/package-overrides.nix
+++ w/pkgs/package-overrides.nix
@@ -507,17 +507,21 @@ in
in
ourPatches ++ upstreamPatches;
-      buildInputs =
-        let
-          replaceOpenssl = pkg:
-            if pkg == pkgs.openssl && lib.versionOlder prev.php.version "8.1" then
-              pkgs.openssl_1_1.overrideAttrs (old: {
-                meta = builtins.removeAttrs old.meta [ "knownVulnerabilities" ];
-              })
-            else
- …
```
> fix: builds on Darwin 

- pkgs/package-overrides.nix
- pkgs/patches/0001-mssql-extension-fix-builds-on-darwin.patch
The mssql extension should work on Darwin, see https://github.com/macports/macports-ports/blob/4187b946818f36f17a78e126780ff901be1e5d0e/lang/php/Portfile#L1408
The build now works on Darwin: https://github.com/fossar/nix-phps/actions/runs/5567766813/jobs/10169895943
Patch inspired by https://github.com/macports/macports-ports/blob/4187b946818f36f17a78e126780ff901be1e5d0e/lang/php/files/patch-php52-ext-pdo_oci-config.m4.diff
> phpExtensions.mssql: fix build on darwin

- pkgs/phps.nix
fixes https://github.com/fossar/nix-phps/issues/305
I tested it locally, everything was fine.
> fix: php <= 7.4 libtool sha256

- pkgs/phps.nix
This PR:
- Originates from #306 
- Replace `fetchpatch2` with `fetchpatch`
> fix: replace `fetchpatch2` with `fetchpatch`

- .github/workflows/build.yaml
- checks.nix
- pkgs/package-overrides.nix
Adds missing mcrypt ext from php-src.
> Adds mcrypt extension for PHP 5.6.40

- .github/dependabot.yml
Hopefully, this will fix broken `DeterminateSystems/update-flake-lock` due to Nix version incompatibility.
> ci: Update GitHub actions with Dependabot

- .github/workflows/build.yaml
- README.md
- flake.lock
- flake.nix
- pkgs/extensions/redis/3.nix
- pkgs/extensions/redis/4.nix
- pkgs/extensions/redis/6.0.nix
- pkgs/libxml2/2.12.nix
- pkgs/package-overrides.nix
- pkgs/phps.nix
```
Warning: PHP Startup: Unable to load dynamic library '/nix/store/gv1fxy87wgndr0y023qphdq7l4r6idjr-php-mysqlnd-8.1.29/lib/php/extensions/mysqlnd.so' (tried: /nix/store/gv1fxy87wgndr0y023qphdq7l4r6idjr-php-mysqlnd-8.1.29/lib/php/extensions/mysqlnd.so (/nix/store/gv1fxy87wgndr0y023qphdq7l4r6idjr-php-mysqlnd-8.1.29/lib/php/extensions/mysqlnd.so: undefined symbol: compress), /nix/store/m86afannv5mjvyh4icmmh15799lacy4k-php-8.1.29/lib/php/extensions//nix/store/gv1fxy87wgndr0y023qphdq7l4r6idjr-php-mysqlnd-8.1.29/lib/php/extensions/mysqlnd.so.so (/nix/store/m86afannv5mjvyh4icmmh15799lacy4k-php-8.1.29/lib/php/extensions//nix/store/gv1fxy87wgndr0y023qphdq7l4r6idjr-php-mysqlnd-8.1.29/lib/php/extensions/mysqlnd.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0 …
```
> php84: init at 8.4.0beta3

- .github/workflows/build.yaml
- checks.nix
- pkgs/package-overrides.nix
[“decimal”](https://php-decimal.github.io) is a PHP extension [I added recently to Nixpkgs in this PR](https://github.com/NixOS/nixpkgs/pull/378564) with the aid of @jtojnar. Here I patch it to make it work for PHP 7, as it requires the JSON extension [which wasn't included in PHP until version 8](https://www.php.net/manual/en/json.installation.php). They also helped me get this working in issue #399.
This PR will have to wait until `flake.lock` is updated, though.
> php7[01234].extension.decimal: Override decimal to allow use in PHP 7

- flake.lock
- pkgs/package-overrides.nix
Patch introduced in https://github.com/NixOS/nixpkgs/pull/398521
> fix: remove patch for `ctype` extension

- .github/workflows/build.yaml
- .github/workflows/upgrade-flakes.yaml
DetSys installer is dropping upstream Nix support:
https://determinate.systems/blog/installer-dropping-upstream/
We could also use `nixbuild/nix-quick-install-action` but that uses single-user installation,
which does not support sandboxing on Darwin:
https://discourse.nixos.org/t/which-github-nix-installer-action-is-faster/25878/10
> ci: Switch to `cachix/install-nix-action`
