fossar/nix-phps

pkgs/phps.nix
Found the next issue... I hope I'm not trying your patience here :worried: 
Aside from not compiling, see https://github.com/NixOS/nixpkgs/blob/3e1be2206b4c1eb3299fb633b8ce9f5ac1c32898/pkgs/top-level/php-packages.nix#L128 for my reasoning on this PR.
Thanks @jtojnar :heart:
=> php56: fix memcached

.github/workflows/build.yaml, pkgs/package-overrides.nix
=> php56.extensions.redis: 3.1.4 → 3.1.6

.editorconfig, .github/workflows/editorconfig-checks.yaml, .github/workflows/upgrade-flakes.yaml
=> ci: Update "Update flake lock" action.

.github/workflows/build.yaml, pkgs/package-overrides.nix, pkgs/tidy-html5.patch
=> #71: Add patch to fix tidy extension and PHP 5.6.

pkgs/package-overrides.nix
Upcoming Nixpkgs bump will remove openssl 1.0, let’s pick up a third party patch to add support for OpenSSL 1.1.
Also, apparently, PHP 7.0 supported OpenSSL 1.1 the whole time.
Fixes: https://github.com/fossar/nix-phps/issues/78
=> php56.extensions.openssl: Apply patch for compat with OpenSSL 1.1

flake.nix, pkgs/phps.nix
- php: more uniform coding style
- flake: replace deprecated `overlay` output
=> Random cleanups

pkgs/php/8.2.nix
https://www.php.net/archive/2022.php#2022-07-07-2
https://github.com/php/php-src/blob/php-8.2.0alpha3/NEWS
=> php82: php82alpha2 -> php82alpha3

pkgs/package-overrides.nix, pkgs/php/8.2.nix
https://github.com/php/php-src/compare/php-8.2.0beta2...php-8.2.0beta3
=> php82: php82beta2 -> php82beta3

pkgs/php/8.2.nix
https://github.com/php/php-src/compare/php-8.2.0beta3...php-8.2.0RC1
=> php82: 8.2.0beta3 -> 8.2.0rc1

pkgs/php/8.2.nix
Announcement: https://externals.io/message/118638
https://github.com/php/php-src/compare/php-8.2.0RC1...php-8.2.0RC2
=> php82: 8.2.0rc1 -> 8.2.0rc2

pkgs/php/8.2.nix
Changelog: https://github.com/php/php-src/blob/php-8.2.0RC3/NEWS
=> php82: php82rc2 -> php82rc3

pkgs/php/8.2.nix
=> php82: php8.2.0rc3 -> php8.2.0rc4

pkgs/php/8.2.nix
News: https://github.com/php/php-src/blob/php-8.2.0RC5/NEWS
=> php82: php8.2.0rc4 -> php8.2.0rc5

pkgs/php/5.6.nix, pkgs/php/7.0.nix, pkgs/php/7.1.nix, pkgs/php/7.2.nix, pkgs/php/7.3.nix, pkgs/php/7.4.nix, pkgs/php/8.2.nix
Similar to https://github.com/NixOS/nixpkgs/pull/193921
=> php82: add sysvsem

pkgs/php/8.2.nix
News: https://github.com/php/php-src/blob/php-8.2.0RC6/NEWS
=> php82: 8.2.0rc5 -> 8.2.0rc6

.github/workflows/build.yaml, .github/workflows/editorconfig-checks.yaml, .github/workflows/upgrade-flakes.yaml
This PR:
- Fix broken "Upgrade flake" action
- Bump action versions
=> ci: update workflows

pkgs/composer/1.x.nix, pkgs/package-overrides.nix
Fixes #196 
```
shyim in nix-phps on  add-composer-1 [?] took 4m15s 
❯ ./result/bin/composer -V
Composer version 1.10.26 2022-04-13 16:39:56
```
=> feat: add composer 1

pkgs/php/7.3.nix, pkgs/phps.nix
Context: #203
* Apply [php/php-src d016434](https://github.com/php/php-src/commit/d016434ad33284dfaceb8d233351d34356566d7d) for php <= 7.2
* Apply pcre1 configure flags for php <= 7.2
=> fix(php72): fix builds on php<=7.2 for darwin

pkgs/composer/2.2.nix
=> php71.packages.composer: 2.2.12 -> 2.12.21

.github/workflows/build.yaml
=> ci: trigger builds on master branch

.github/workflows/build.yaml, README.md, flake.nix, pkgs/phps.nix
Enable this when:
1. PR #242 has been merged
2. PR https://github.com/NixOS/nixpkgs/pull/239151 has been propagated.
Status: https://nixpk.gs/pr-tracker.html?pr=239151
=> php83: enable

pkgs/composer/1.x.nix, pkgs/composer/2.2.nix
Security releases!
Changelogs in commit log messages.
=> {composer1, composer2}: bumps

.github/workflows/build.yaml
=> ci: build on `aarch64-darwin`

pkgs/composer/2.2.nix
Fix a couple of CVEs
This should fix https://github.com/fossar/nix-phps/issues/347
cc @DanielSiepmann !
=> php71.packages.composer: 2.2.22 -> 2.2.24

.github/workflows/nix-fmt-checks.yaml, checks.nix, flake.nix, pkgs/composer/1.x.nix, pkgs/composer/2.2.nix, pkgs/enchant/1.x.nix, pkgs/extensions/blackfire/1.50.0.nix, pkgs/extensions/blackfire/1.88.1.nix, pkgs/extensions/datadog_trace/0.75.0.nix, pkgs/lib.nix, pkgs/libxml2/2.12.nix, pkgs/package-overrides.nix, pkgs/php/5.6.nix, pkgs/php/7.0.nix, pkgs/php/7.1.nix, pkgs/php/7.2.nix, pkgs/php/7.3.nix, pkgs/php/7.4.nix, pkgs/php/8.0.nix, pkgs/phps.nix
Supersedes https://github.com/fossar/nix-phps/pull/190
=> Format with nixfmt-rfc-style

pkgs/package-overrides.nix
context: https://github.com/NixOS/nixpkgs/pull/400894
=> ctype: adjust version constraints
